os: Visual Studio 2015
environment:
  matrix:
    # MSVC Toolchains
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc

    # GNU Toolchains
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu
matrix:
  allow_failures:
    - channel: nightly
cache:
  - '%USERPROFILE%\.cargo'
  - target
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version
  - cargo --version
build: false
test_script:
  - cargo check --all
  - cargo check --all --features display-fps
  - cargo test --all
  - cargo test --all --release
